package org.training.leisure.swimmingpool;

import java.lang.Number;
import org.training.leisure.swimmingpool.Period;
import org.training.leisure.swimmingpool.SeasonType;

rule "InsertEnumRule"
    dialect "java"
    salience 100
    when
        InsertPeriod(eVal : enumValue != null)
    then
        Period p = new Period();
        p.setSeasonType( SeasonType.valueOf(eVal));
        insert (p);
end